apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistem-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistem-inventory
  template:
    metadata:
      labels:
        app: sistem-inventory
    spec:
      containers:
        - image: zdays/sistem-inventory:latest
          name: sistem-inventory
          env:
            - name: SISTEM_INVENTORY_DATABASE_HOST
              value: db.recompile.it
            - name: SISTEM_INVENTORY_DATABASE_PORT
              value: "5432"
            - name: SISTEM_INVENTORY_DATABASE_DB_NAME
              value: sistem_inventory
            - name: SISTEM_INVENTORY_DATABASE_SSL_MODE
              value: require
            - name: SISTEM_INVENTORY_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sistem-db
                  key: username
            - name: SISTEM_INVENTORY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sistem-db
                  key: password
            - name: SISTEM_INVENTORY_MICROSERVICES_USERS_URL
              value: http://10.0.195.94:8080/api/v1
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sistem-inventory
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: sistem-inventory
